// One locally hosted crest per club or national team. Repeated teams reuse the
// same file regardless of how many shirts they have in the collection.
export const teamLogos = Object.freeze({
  "AC Milan": "logos/ac-milan.svg",
  "AS Roma": "logos/as-roma.svg",
  Ajax: "logos/ajax.svg",
  "Al Hilal SFC": "logos/al-hilal.svg",
  Argentina: "logos/argentina.svg",
  "Boca Juniors": "logos/boca-juniors.svg",
  Brazil: "logos/brazil.svg",
  "Chelsea FC": "logos/chelsea-fc.svg",
  "Côte d’Ivoire": "logos/cote-divoire.svg",
  "FC Barcelona": "logos/fc-barcelona.svg",
  France: "logos/france.svg",
  Germany: "logos/germany.svg",
  Ghana: "logos/ghana.svg",
  Guatemala: "logos/guatemala.svg",
  "Inter Miami": "logos/inter-miami.svg",
  Japan: "logos/japan.svg",
  Juventus: "logos/juventus.svg",
  "Manchester City": "logos/manchester-city.svg",
  "Manchester United": "logos/manchester-united.svg",
  "Paris Saint-Germain": "logos/psg.svg",
  Portugal: "logos/portugal.svg",
  "Santos FC": "logos/santos-fc.svg",
  "Saudi Arabia": "logos/saudi-arabia.svg",
  Spain: "logos/spain.svg",
  "Sporting CP": "logos/sporting-cp.svg",
  "Venezia FC": "logos/venezia-fc.svg",
});
